services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: lobzikai
      POSTGRES_PASSWORD: lobzikai
      POSTGRES_DB: lobzikai
    ports:
      - "127.0.0.1:22546:5432"
    volumes:
      - ./.devdata/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:40601:5672"
      - "127.0.0.1:12516:15672"
    volumes:
      - ./.devdata/rabbitmq:/var/lib/rabbitmq
