name: lobzikai

services:
  asr:
    build:
      context: ../..
      dockerfile: apps/asr/Dockerfile
    restart: unless-stopped
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    env_file:
      - ../../.env
    volumes:
      - ../../cache:/app/asr/cache
