"""empty message

Revision ID: d3780e7125b3
Revises: 99852c3ca4f4
Create Date: 2025-10-05 23:01:49.307995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3780e7125b3'
down_revision: Union[str, Sequence[str], None] = '99852c3ca4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('show_questions_section', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lecture', sa.Column('show_askai_section', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'show_askai_section')
    op.drop_column('lecture', 'show_questions_section')
    # ### end Alembic commands ###
